UMN-LATIS/bluesheet

app/Http/Controllers/SchedulingController.php
app/Library/Bandaid.php
routes/web.php

Add endpoints to feed the scheduling report, with information about classes, terms, instructors and leaves.

Scheduling Report Data Generation

---

resources/js/components/EditGroup.vue
resources/js/components/MemberList.vue
resources/js/components/Members.vue

Resolves:
- #39 
Also fixes an issue where a user adding a new role to one member, wouldn't see that new role as an option in the roles dropdown for other members.

fix roles not listing in Combobox

---

app/Console/Commands/ImportLeaves.php
app/Console/Kernel.php
app/Library/Bandaid.php
app/Library/UserService.php
app/User.php
resources/js/components/ViewGroup.vue

Adds a nightly job which imports leaves from bandaid. Won't recreate leaves if they've been deleted, and if a leave already exists with the exact same start/end dates (even if it's manually created), a new entry won't be added.

Import Leaves from Bandaid

---

app/Http/Controllers/GroupController.php
resources/js/pages/ReportListPage.vue
resources/js/pages/reports/GroupAdmins.vue
resources/js/router.ts
routes/web.php

this was requested by Christopher as part of their efforts to enhance responsibility for group updates.

add a report for group admins

---

app/Http/Resources/Group.php

Cast `show_unit` to boolean in GroupResource

---

.eslintrc.cjs
package.json
resources/js/App.vue
resources/js/app.js
yarn.lock

Resolves #25
This removes v-tour stuff from the frontend. Backend columns are left in place, in case we want to bring it back again.

Strip tour stuff

---

app/Console/Commands/ImportSSLAndMidcareerEligibility.php
app/Console/Commands/importSabbaticalEligibilty.php
app/Http/Controllers/LookupController.php
app/Http/Controllers/SchedulingController.php
app/Http/Controllers/UserController.php
app/Http/Resources/CourseWithInstructors.php
app/Http/Resources/User.php
app/Library/Bandaid.php
app/User.php
database/migrations/2023_09_12_175430_add_ssl_and_midcareer_flags_to_users.php
resources/js/components/ViewUser.vue
resources/js/pages/ReportListPage.vue
resources/js/pages/reports/EligibilityReport.vue
resources/js/pages/reports/SchedulingReport/ReportRow.vue
resources/js/router.ts
resources/js/types.ts
routes/web.php

Throwing this over the wall as is, as I'm not going to have time to keep tweaking on this for the next day or two. I'm fine with merging it as is, but if some of my report hackery is too much, feel free to grab it and tweak :)

SSL and MidCareer Importing

---

resources/js/components/ViewUser.vue

hide eligibility label on user page if no eligibility

---

app/Group.php
app/Http/Resources/Membership.php
app/Http/Resources/MembershipWithGroups.php
app/Leave.php
app/User.php
composer.json
composer.lock
database/migrations/2024_02_05_230032_sanctum_v3_add_expires_at_column.php
deploy.php
phpunit.xml
tests/cypress/integration/ui/groupCreation.test.ts

Not the latest version, but close. There's an open issue with 10.43.0 which current breaks `after:date` validation.
Having some weird issue deploying to dev: deployer can't seem to find the remote branch on the host. I'll check it out more tomorrow.

Update to Laravel 10

---

resources/js/pages/CoursePlanningPage/stores/usePersonStore.ts

Resolves #87
Resolves #88 
On dev: https://cla-groups-dev.oit.umn.edu/course-planning/groups/23

fix sorting in Person table in course planning

---

README.md
docs/using-bluesheet.md
resources/js/components/ViewGroup.vue
resources/js/pages/CoursePlanningPage/CoursePlanningPage.vue

Scheduling Report: Rename to "Faculty Leaves Planning Report"

---

resources/js/components/GanttRow.vue

Add role with name in Gantt view

---

resources/js/components/EditGroup.vue

Resolves #122 
Validates dept id. Shows an input error if invalid, and a message in the modal if user attempts to save.
On dev.

check that dept id input on Edit Group page is a number

---

app/Http/Controllers/LeaveController.php
app/Http/Resources/LeaveResource.php

Add deptID to leaves api user data

---

app/Http/Controllers/CoursePlanning/GroupSectionController.php

resolves #177 
on dev for testing

fix: some faculty sections not showing if they have the same course number

---

resources/js/stores/useUserStore.ts

current user may be fetched multiple times if a a request is in flight

fix repeat fetching current user

---

resources/js/pages/CoursePlanningPage/stores/useCoursePlanningStore.ts
resources/js/pages/CoursePlanningPage/stores/useLeaveStore.ts

Remove noisy leftovers from #191

---

app/Http/Controllers/CoursePlanning/GroupCourseController.php
app/Http/Controllers/CoursePlanning/GroupEnrollmentController.php
app/Http/Controllers/CoursePlanning/GroupSectionController.php
app/Library/Bandaid.php

Now all of the instructor's classes will be shown, not just the departmental classes.
On dev.
Resolves #180

show all classes for dept instructors in leave report

---

resources/js/components/LeavesTable/LeaveTableRow.vue

fixes an issue where the leave stays in "edit mode" even after saving

fix: leave remains in edit mode after save

---

resources/js/components/ComboBox.vue

- adds floatingui's autoupdate for positioning of combobox
on dev

fix: wonky positioning of combobox in add member modal

---

resources/js/pages/CoursePlanningPage/CoursePlanningPage.vue

scroll to current term on term filter change

---

resources/js/components/LeavesTable/LeaveTableRow.vue
resources/js/components/LeavesTable/SelectLeaveDate.vue

Adds an error message if the end date is before the start date.
On dev.

show error message if end date before start date
