resources/js/components/Members.vue
Adds group info to CSV member export:
- group name
- group abbrevation
- link to group
Resolves #5 
I like the suggestion to add UMN official group codes (e.g. dept numbers) to a group and including this in the CSV export, but I wasn't sure if this info is in bluesheet.
[Example CSV Export](https://docs.google.com/spreadsheets/d/1brmO-KQ8ljsAdqM7l3l6PD2uCwHGUI4pSFk2XOvOdfU/edit?usp=sharing)
<a href="https://docs.google.com/spreadsheets/d/1brmO-KQ8ljsAdqM7l3l6PD2uCwHGUI4pSFk2XOvOdfU/edit?usp=sharing">
</a>
=> Add Group Name and Abbreviation to CSV

resources/js/components/LeaveChip.vue
This removes underscores when rendering leave types, so `COURSE_RELEASE LEAVE` becomes `COURSE RELEASE LEAVE`
Fixes #48
=> Remove underscore from leave types

resources/js/pages/reports/SchedulingReport/SchedulingReportPage.vue
Previously, Select All would act like a "Clear All":  it would clear the filters if any were selected, and only select all if none were selected. This flip flops things so it behaves as expected.
=> fix select all on filters

app/Http/Resources/CourseWithInstructors.php, resources/js/api.ts, resources/js/pages/reports/SchedulingReport/ReportRow.vue, resources/js/pages/reports/SchedulingReport/SchedulingReportPage.vue, resources/js/types.ts
This resolves two issues I noticed when looking at the scheduling report for Writing Studies:
- Instructors with "Unspecified" appointments would show up even when the "Unspecified" filter was unchecked
- Appointment and course types were in a random non-alphabetical order.
These instructors had a space in their appt type, and the logic for trimming and binning with the other nulls wasn't quite right because it used nullish coalescing (`??`) instead of "or" (`||`) to fallback.
Handling all the trimming and fallback logic in the view layer was fussy, so this PR moves the fallback work upstream into the api layer. 
Additionally, instructor appointment types and course types are now sorted alphabetically.
Up on dev:  https://cla-groups-dev.oit.umn.edu/reports/schedulingReport/24
With PR, …
=> Fix: instructors with "Unspecified"  appointments appearing even when "Unspecified" was unchecked

resources/js/pages/GroupListPage.vue
Resolves #12
On the browse groups page, the breadcrumb box can read as a search input and the search input can read as a button to new users. This removes the background on the breadcrumbs and increases  the width of the search input a little:
Before:
After:
=> differentiate breadcrumb + search input on Browse Groups page

package.json, resources/js/App.vue, yarn.lock
This resolves an issue where the app menu may overflow the container:
`@umn-latis/cla-vue-template` is updated to the latest version which supports configurable breakpoints and changes the fallback to flex-wrap. The app-header's new breakpoint is set to `xl` (1280px).
Fixes #34
=> Increase Breakpoint on App Header

resources/js/components/PersonSearch.vue, resources/js/components/UserLookup.vue
Background:
When typing in the person search field, the dropdown appears with a list of buttons that are choices to complete the user.
The intended functionality is: when there's there's no focus within the person search, the menu should disappear. This was accomplished with CSS:
```
.person-search:not(:focus-within) .person-search__results {
display: none;
}
```
This works well in Chrome and Firefox. But,[Safari behaves differently](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus). Clicking a button doesn't give the button focus in safari. Since the clicked button has no focus, there's no focus within the person search component thus hiding the list of options before the click lands.
So, the pithy CSS has to go. This PR reworks the component to use JS …
=> Fix: autocomplete clicking in safari

resources/js/api.ts, resources/js/components/SelectGroup.vue, resources/js/pages/reports/SchedulingReport/SchedulingReportPage.vue, resources/js/types.ts
Adds a select to the Scheduling Report that lets users choose whether the generate the report for TA's or Primary Instructor's.
For testing: https://cla-groups-dev.oit.umn.edu/reports/schedulingReport/10
Details:
- The filters for report generation is getting complicated. This may work better as tabs, but I think I'll defer UI reorg until #71 is done.
- This contains no client side caching: changing from PI to TA and back will regenerate the report. If users are likely to do a lot of switching back and forth, LMK, and I can add some caching.
- I'm not sure about the labels. What language would users use when referring to "Instructor Role?"
=> Scheduling Report viewer can choose `TA` or `PI` roles for report

resources/js/pages/CoursePlanningPage/components/EditDraftSectionModal.vue, resources/js/pages/CoursePlanningPage/components/PersonTable/PersonTable.vue, resources/js/pages/CoursePlanningPage/components/PersonTable/PersonTableCell.vue, resources/js/pages/CoursePlanningPage/components/PersonTable/SectionDetails.vue, resources/js/pages/CoursePlanningPage/stores/useRootCoursePlanningStore.ts, resources/js/stores/useTermsStore.ts
This resolves an issue where depts may have some terms in the near future that still need planning. 
Previously, it was assumed that if any sections were scheduled in a given term, planning was complete for the given term AND previous terms.  However, this may not be the case. For example, a dept may have primary instructors assigned for Fall 2024, but may still be in planning stage for the previous term (Summer 2024).
This would cause the number of plannable terms to be miscalculated. (A related bug happens if a dept intentionally doesn't schedule any classes for a term).
Now, any term more than 2 months out will be plannable – even if it has some published sections.
=> permit all future terms to be plannable

resources/js/pages/CoursePlanningPage/components/PersonTable/PersonTableCell.vue, resources/js/pages/CoursePlanningPage/components/PersonTable/SectionDetails.vue, resources/js/pages/CoursePlanningPage/components/PersonTable/UnpublishedSectionDetails.vue
This resolves an issue where some course sections were not showing up.
The issue was caused by a change in #83 for how `isViewable`  works. `isViewable` prop only pertains to unpublished sections, so the prop has been renamed as `isUnpublishedViewable`.
Up on dev for testing
=> Fix only course sections not showing up

resources/js/components/DragDrop/DragDrop.vue, resources/js/components/DragDrop/useDragDropStore.ts, resources/js/components/DraggableCard.vue, resources/js/pages/CoursePlanningPage/components/CourseTable/CourseTable.vue, resources/js/pages/CoursePlanningPage/components/CourseTable/CourseTableCell.vue, resources/js/pages/CoursePlanningPage/components/CourseTable/CourseTableCourseRow.vue, resources/js/pages/CoursePlanningPage/components/CourseTable/EnrollmentInPublishedSection.vue, resources/js/pages/CoursePlanningPage/components/CourseTable/EnrollmentInUnpublishedSection.vue, resources/js/pages/CoursePlanningPage/components/EditDraftSectionModal.vue, resources/js/pages/CoursePlanningPage/components/PersonTable/PersonTableCell.vue, resources/js/pages/CoursePlanningPage/stores/useCourseSectionStore.ts, resources/js/types/index.ts
Previously, users could plan future course sections from the Instructors and Teaching Assistants tab. This adds similar functionality to the Courses tab.
On https://cla-groups-dev.oit.umn.edu/course-planning/groups/23 for testing.
Closes #90
=> Add course planning functionality to Courses Tab on Leaves Scheduling Report

resources/js/components/Members.vue, resources/js/components/SortableLink.vue, resources/js/components/ViewGroup.vue, resources/js/pages/reports/EligibilityReport.vue, resources/js/pages/reports/FiscalReportPage.vue, resources/js/types/index.ts, resources/js/utils/index.js, resources/js/utils/sortByValueAtPath.ts
Resolves #80 
This resolves sorting issues on the groups page, and in a few reports. The issue was that `currentSort` and sortable fields could be an object path like `user.surname` or `financeManager.0.user.displayName` not just a property name. I missed this when migrating to Vue3... any sort based on paths has probably been broken since then.
- As I was working through the issue, I added types to `<MemberList>` and `<SortableLink>` components.
- extracted the sort function to its own util, so it could be reused wherever broken
- added [some deduplication](https://github.com/UMN-LATIS/bluesheet/blob/97c39d0c6c76455fe1933c50ade5b0e03fe2f2c5/resources/js/pages/reports/FiscalReportPage.vue#L161-L162) to the the Fiscal Report. Vue was complaining multiple entries with the same dept id. (Is …
=> Fix sorting on Group page and some reports

resources/js/pages/reports/FiscalReportPage.vue
=> Fiscal Report page refers to non-existant "show email list" button

resources/js/components/LeavesTable/LeavesTable.vue
Fixes #106
Removes the extra <tbody> wrapping the main contents. 
We're using <tbody> to wrap the leave artifact details section. (There was probably a better way to go about this layout, but I wanted the details columns to align with the main artifact columns.)
Whatever the case, nested <tbody> is causing the problem. Tables can have multiple <tbody>, but I guess nested <tbody> is invalid. To resolve, this removes the main wrapping tbody.
=> Layout for Leave Artifacts broken

app/Library/Bandaid.php, app/Library/UserService.php
- change how we're getting dept employees to fix issue where some courses aren't appearing if the instructor isn't technically part of the department
- remove wrapping post request with `form_params`.
- use names table for fallback if LDAP getting fails, and do a best attempt to create user
=> fix: Bandaid::getEmployees

deploy.php
Resolves #118 
The resulting task-tree:
```
└── deploy
├── deploy:prepare
│   ├── deploy:info
│   ├── deploy:setup
│   ├── deploy:lock
│   ├── deploy:release
│   ├── deploy:update_code
│   ├── deploy:git:submodules  // after deploy:update_code
│   ├── yarn:install  // after deploy:update_code
│   ├── assets:generate  // after yarn:install
│   ├── deploy:shared
│   └── deploy:writable
├── deploy:vendors
├── artisan:storage:link
├── artisan:cache:clear  // before artisan:config:cache
├── artisan:config:cache
├── artisan:route:cache
├── artisan:view:cache
├── artisan:event:cache
├── artisan:migrate
├── artisan:queue:restart  // after artisan:migrate
└── deploy:publish
├── artisan:migrate  // before deploy:symlink
├── artisan:queue:restart  // after artisan:migrate
├── deploy:symlink
├── …
```
=> clear cache on deploy

resources/views/base.blade.php
Adds the name of the impersonated user and a "Leave Impersonation" button to the top of the page when a user is impersonated.
Before, there actually was a link – but it was easily lost below the footer.
Fixes #121
=> Add "Leave impersonation" button to top of page when impersonation

resources/js/components/InputGroup.vue, resources/js/components/LeavesTable/LeaveArtifactRow.vue, resources/js/components/LeavesTable/LeaveTableRow.vue
Resolves an issue where the `<Label>`'s `:required` prop was hard-coded to `true` in the `<InputGroup>`. This would mark non-required fields as optional.
Also adds "required" prop to any `InputGroup`'s requiring an input.
This issue came up when working on #112.
=> fix: <InputGroup> not passing `required` prop to `<Label>`

resources/js/features/course-planning/components/CoursePlanningFilters.vue, resources/js/features/course-planning/stores/useCoursePlanningStore.ts, resources/js/types/index.ts
This permits users to filter displayed sections based on their enrollment count. Defaults to 0.
Closes #102.
=> Leave Planning Report: Add filter for minimum section enrollment.

app/Http/Resources/MembershipWithGroups.php, database/migrations/2024_03_22_025035_change_group_admin_role_to_global-group-admin.php, database/seeders/TestUsersSeeder.php
This is related to work on scoping group admin permissions to specific groups and #92 .
Currently, there's a `group admin` role (Spatie Role) permits administration of any group or user leaves. This is different than permissions granted when the `admin` flag is set on a member of a group. This renames the role to `global group admin` to make thnigs clearer until scoping work is complete and we can migrate users with global permissions to scoped permissions. After that functionality is done, we may be able remove this role all together.
On dev for testing
=> rename `group admin` role as `global group admin`

resources/js/api/api.ts, resources/js/pages/UserHomePage.vue, resources/js/types/index.ts
A default `view user` should be able to see other user's data and roles, but not their leaves. When a `view user` requests data from the api, the `leaves` property on the user object will be undefined. This is correct, but not properly handled on the front end.
Currently, the frontend expects users to have the same shape, with a defined (but possibly empty) `leaves` list. So userStore throws an error when mapping over the undefined `leaves` resulting in a blank page for the `view user`.
This PR handles undefined leaves value from the API. 
- the type of the `ApiUserResponse` is updated to account for undefined leaves.
- undefined leaves values are transformed into empty leaves array so that all user data has the same shape.
- to handle leave viewing, rather than using defined …
=> fix user page rendering for default users

app/Http/Controllers/CoursePlanning/GroupLeaveController.php, app/Library/UserService.php
Fixes #135
`UserService::getDeptInstructors` can now optionally refresh the cache. `GroupLeaveController@index` will always ask for fresh data.
Not deployed (yet) to dev, but this is what it looks like locally:
https://github.com/UMN-LATIS/bluesheet/assets/980170/a9058a1b-a18e-4eaf-aaad-3dee4b7bf404
=> fix: leaves planning report doesn't always show newly created leaves because of cache

resources/views/admin/users/edit.blade.php
Adds impersonate user to admin "edit" view in addition to "show" view. This makes the flow for testing group managers a bit easier.
Fixes #138
=> add "impersonate user" to the  admin "edit" view

app/Http/Controllers/UserController.php, resources/js/components/UserLookup.vue
Previously, when Find User fails, the axios interceptor would display a 500 error modal.
This:
- disables "Find User" button when input is empty
- returns 404 instead of 500 when user(s) not found
- skips axios error notification interceptor so that we can manually handle error
- fix error message
resolves #119 
on dev for testing
=> improve error handling for lookup user

resources/js/components/MemberList.vue, resources/js/components/Members.vue
When a user has the global `edit groups` permissions, the `Group Admin` column will show up in view mode to make it easier to see which users have been granted admin permissions.
=> show admin column in Group view mode if user can edit groups

resources/js/components/LeavesTable/LeaveTableRow.vue, tests/cypress/integration/userLeaves.test.ts
When a user clicks "Add Leave" and then cancel, the leave will persist in the local store – showing an extra row to the users. (No actual new leave is created.)
This fixes the issue, removing the leave from the local store when the Cancel button is clicked. Adds a corresponding test.
=> fix: cancelling a new leave

docs/index.md, docs/using-bluesheet.md, resources/js/components/Members.vue, resources/js/pages/ReportListPage.vue, resources/js/pages/reports/GroupAdmins.vue
This changes the nomenclature of "Group Admin" to "BlueSheet Manager" throughout the app.
=> change "Group Admin" to "BlueSheet Manager"

app/Group.php, app/Policies/LeavePolicy.php, app/User.php, tests/Feature/api/leaves/DeleteLeavesTest.php, tests/Feature/api/leaves/GetLeaveByIdTest.php, tests/Feature/api/leaves/PostLeavesTest.php, tests/Feature/api/leaves/PutLeavesTest.php, tests/Feature/api/users/leaves/GetAllUserLeavesTest.php, tests/cypress/integration/userLeaves.test.ts
Leaves and Leave Artifacts are now accessible to users who manage a parent group of the leave owner.
- added `$group->getDescendentGroups` which will recursively get any child groups of the given group (and any child groups of that, and so on).
- updated `$user->getManagedGroups()` to return any directly managed groups and any descendent subgroups of managed groups.
Closes #139
=> BlueSheet managers can view/modify leaves of subgroup members

app/Policies/LeavePolicy.php, tests/Feature/api/permissions/LeavePermissionsTest.php
The `LeavePermissionsController` references the `LeavePolicy::createLeavesForGroup` method, but that method is missing.   This adds it. This issue came up while working on #92. Some tests (originally part of #92 work) are added as well.
=> fix `api/permissions/groups/{groupId}/leaves` endpoint

tests/cypress/integration/groupCreation.test.ts
This modifies the group creation test so that they can be run independently if one fails. 
- refreshes the DB after each test so there's no leaking state
- creates a group for the edit test. Previously, this test was relying on the previous `create` test.
=> tests: makes group creation e2e tests so they can run independent

app/Http/Controllers/GroupController.php, app/Policies/GroupPolicy.php, app/Policies/LeavePolicy.php, tests/Feature/api/group/PostGroupTest.php, tests/Feature/api/permissions/LeavePermissionsTest.php
As part of #92 , we want group managers to be able to create subgroups of any group they manage.
This updates `POST /api/groups` so that users may submit an optional `parentGroupId` with their POST request. `GroupPolicy::create` is updated so that it checks if parentGroup is managed by the current user.
=> Update api to permit group managers to create a subgroups (stacked on #147)

app/Http/Controllers/GroupController.php, app/Http/Controllers/GroupPermissionController.php, resources/js/api/api.ts, resources/js/components/CreateGroup.vue, resources/js/components/ViewGroup.vue, resources/js/stores/useGroupStore.ts, resources/js/stores/usePermissionsStore.ts, routes/web.php, tests/Feature/api/group/PostGroupTest.php, tests/Feature/api/permissions/SubgroupPermissionsTest.php, tests/cypress/integration/groupCreation.test.ts
This:
- adds functionality for group managers to create subgroups on the GroupsPage (Note: This PR is focused on functionality. A forthcoming PR will update the layout.)
- adds endpoint for checking if currentUser has permissions to update subgroups
- move create group functionality to the GroupStore. When a new group is created, the store is updated. Additionally, the parent's child groups are updated.
- changes the `POST /api/group` to return the new group. Previously, it returned the id and a status message.
Closes #92
=> add ui to permit group managers to create subgroups

app/Group.php, app/Http/Resources/Group.php, app/Policies/GroupPolicy.php, app/User.php, resources/js/components/ViewGroup.vue, resources/js/types/index.ts, tests/Feature/api/group/PatchGroupTest.php
- changes the GroupPolicy `update` and `delete` methods to check if a $user manages a group or subgroup
- updates the `GroupResource` to return permissions akin to other resources. These permission checks defer to the GroupPolicy.
```json5
canCurrentUser: { update: true, delete: true },
```
This replaces the previous `user_can_edit` property property.
- updates the frontend to use `group.canCurrentUser.update` to determine if edit button should be displayed
- simplifies other GroupPolicy
- removes the old `Group::userCanEdit` method as policy checks are now done directly.
- adds test for editing groups via api
on dev for testing
=> Permit BlueSheet manages to edit subgroups

resources/js/components/MemberList.vue, resources/js/components/Members.vue
This fixes an issue where users with 'edit group' permissions would see the BlueSheet manager column on the `RolesPage` causing some weird formatting.
Before:
This is because `RolesPage` and `GroupPage` share a `MemberList` component that shows different things depending on the `viewType` prop. 
Render logic is updated to check viewType.
After:
on dev for testing
=> fix: don't show bluesheet manager check column on RolesPage

resources/js/components/Gantt.vue, resources/js/components/MemberList.vue, resources/js/components/Members.vue, resources/js/components/SortableLink.vue
This fixes the gantt chart table header rendering.
BEFORE: Name and dates appear as separate broken rows
AFTER: Single row
Previously, the headers were in a different component as table body. This made it easy for a header/body column mismatch. 
This turns the `MemberList` and `Gantt` components into full tables, including their column headers. Sorting props are passed down, and then when a SortableLink is clicked, a sort event is emitted so that both components keep the correct order.
Sortable Link is changed to a button element for accessibility. (Previously it was a `<span>`).
On dev for testing.
=> Fix weird gantt chart header formatting

resources/js/components/Button.vue, resources/js/components/EditGroup.vue, resources/js/components/InputGroup.vue, resources/js/components/ViewGroup.vue, resources/js/utils/index.ts, resources/js/utils/isValidUrl.ts, tests/cypress/integration/groupCreation.test.ts
- Changes to `<InputGroup>` component for artifact input and adds validators to label and target field.
- shows error when attempting to save with missing artifact label or invalid target url
closes  #157
=> fix error when group artifact is submitted without url

resources/js/components/EditGroup.vue
In the Add Member Modal,  this clears the name input field once a user is selected. Fixes #158
=> clear add member modal after adding a member successfully

resources/js/components/EditGroup.vue
The edit group page can be quite long, and it's easy to lose track of where to save. This makes the top save/cancel buttons sticky when scrolling and adds a page header.
=> Edit Group Page: make save buttons sticky to the top

resources/js/components/EditGroup.vue, resources/js/components/InputGroup.vue, resources/js/components/MemberList.vue, resources/js/components/Members.vue, tests/cypress/integration/groupCreation.test.ts
- put the top form inputs in a grid
- moved notes and artifacts to a sidebar
- fixed some alignment in memberlist column (centered checkbox and remove button in column)
Closes #161 
Before | After
=> Group page edit form tidying

resources/js/components/Members.vue
=> fix spacing between Show Email List button and Search Icon

resources/js/components/ManagerBadge.vue, resources/js/components/MemberList.vue, resources/js/components/Members.vue, resources/js/components/Roles.vue, resources/js/pages/UserHomePage.vue
Currently, there's no straight forward way for a user to see which groups they can manage.
- adds a "Manager" badge next to User page, Group page, and Roles page.
- removes the redundant BlueSheet Manager column on the Group page when in view mode. Edit mode retains the BlueSheet Manager  checkbox column, of course.
User Page:
Group page, View mode:
Group page, Edit mode:
Roles page
On dev for testing
=> denote group managers in roles and members list with a badge

.github/workflows/tests.yml, app/Http/Resources/PersonResource.php
Return an empty string instead of null for missing given/surnames – I ran into null values for some users (running locally with an old db), which caused the LeavesReport to throw and whitescreen when sorting.
=> fix: leaves report whitescreens when given/surname is null

app/Library/Bandaid.php
In previous PR, we changed the allow_redirects option to false in the Bandaid service to fix a failing CI test:
```
Http::globalOptions([
'allow_redirects' => false,
]);
```
The side effect was that `Bandaid::getTerms()` would fail because it relied on a redirect. It's url `/classes/terms/` contained a trailing slashes, which previously would be redirected to `/classes/terms` (no trailing slash).
This removes the trailing slash to resolve the issue.
=> fix: null returned from getTerms()

resources/js/pages/CoursePlanningPage/components/PersonTable/PersonTableCell.vue
Sorts sections listed in planning report cells.
Closes #178
=> sort sections in planning report instructor table 

app/Library/Bandaid.php, resources/js/pages/CoursePlanningPage/stores/useCoursePlanningStore.ts, resources/js/pages/CoursePlanningPage/stores/useLeaveStore.ts
Resolves an regression after #191  where some leaves would not appear in the dept leave report if they're leave start/end dates were in the liminal space between terms (like the term payroll leave dates).
Accidentally swapped the dates after #191, and then "fixed" the broken test by casting strings to Carbon object.
=> Fix regression: some leaves do not appear in leave report (stacked on #193)

app/Library/Bandaid.php
fixes angry red squiggles in vscode. `Bandaid::cachedGet` uses `json_decode` to parse body, with the default `false` option – which returns an object not and array. But, the PHPDocs indicate that an array is returned in some places, incorrect type error messages in vscode.
=> fix phpdocs for `getDeptClassList` and  `getTerms`

resources/js/components/LeavesTable/LeaveTableRow.vue, resources/js/components/LeavesTable/SelectLeaveDate.vue
When editing a Leave, the end date will show with the "custom date input" even though it's a term date. This is because valid options change after component is mounted, either after loading, or after the start date is selected.
This changes from an onMounted check to watching when leave date options change.
on dev
=> fix: leave remains in edit mode after save (stacked on #198)

app/Library/Bandaid.php
301 is returned from api because of the trailing `/`. We're not following redirects, so this error is thrown:
```
App\Library\Bandaid::getDepartments(): Return value must be of type array, null returned
```
=> fix: `Bandaid::getDepartments`

resources/js/pages/CoursePlanningPage/stores/useCoursePlanningStore.ts
This adjusts the leave report filter logic to show instructors who have leaves, but may not have any taught sections that are visible (because of say, term filters).
removes the check to only show people with visible sections.
Resolves #203
On dev (tho the screenshot is from local)
=> fix: instructors with leave not appearing in leave report

app/Http/Controllers/CoursePlanning/GroupPersonController.php, app/Http/Resources/DeptInstructorResource.php, app/Library/UserService.php, resources/js/pages/CoursePlanningPage/CoursePlanningPage.vue, resources/js/pages/CoursePlanningPage/components/CoursePlanningFilters.vue, resources/js/pages/CoursePlanningPage/stores/useCoursePlanningStore.ts, resources/js/pages/CoursePlanningPage/stores/usePersonStore.ts, resources/js/types/index.ts, tests/Feature/api/users/leaves/GetAllUserLeavesTest.php
This adds a new filter to the Dept Leaves report, allowing users to choose whether to show only currently active dept employees or all department employees.
`UserService::getDeptInstructors()` is updated to add a new `hasActiveDeptAppointment` property to each instructor. The method adds an api request to Bandaid to get the current dept employee list, and then compares this active list with the list of all instructors. We could probably optimize this further (maybe just returning the active status directly from bandaid?) if needed.
On the frontend, the  a new `onlyActiveAppointments` filter is added to the course planning store. By default, this is true – only active instructors will be shown in the report. 
One gotcha was with the TA tab – the new 'only active' default seems to prevent …
=> leave report: add filter for dept employee appt status

resources/js/components/DownloadSpreadsheetButton.vue, resources/js/pages/CoursePlanningPage/helpers/coursePlanningFilters.ts, resources/js/pages/CoursePlanningPage/helpers/getListOfTermLeaves.ts, resources/js/pages/CoursePlanningPage/helpers/getPersonTableRows.ts
Use appointment status filter when creating the downloadable leaves report spreadsheet.
resolves #209
=> fix(leaves report): spreadsheet doesn't use active status filter
